name: emotion_detector2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  tensorflow_lite_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: "assets/1.png"
  android: true
  ios: true
  fullscreen: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/
  
  
  